name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: fake-api-key
      OPENAI_ORGANIZATION_KEY: fake-org-key
    strategy:
      matrix:
        include:
          - pair:
              elixir: 1.14.3
              otp: 24.3
            build-flags: --warnings-as-errors
          - pair:
              elixir: 1.14.3
              otp: 25.1
            build-flags: --warnings-as-errors
          - pair:
              elixir: 1.15.7
              otp: 26.1
            build-flags: --warnings-as-errors
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pandoc
        uses: nikeee/setup-pandoc@v1

      - name: Setup Elixir Project
        uses: ./.github/actions/elixir-setup
        with:
          elixir-version: ${{ matrix.pair.elixir }}
          otp-version: ${{ matrix.pair.otp }}
          build-flags: --all-warnings ${{ matrix.build-flags }}

      - name: Run Tests
        run: mix test ${{ matrix.build-flags }}
        if: always()
